import type { ArticleSource } from "@tulmek/core/ports";
import type { FeedArticle, HubCategory, FeedMetadata } from "@tulmek/core/domain";
import feedData from "@/content/hub/feed.json";
import metadataData from "@/content/hub/metadata.json";

/**
 * Static JSON adapter for ArticleSource port.
 *
 * Reads articles from bundled JSON files generated by the aggregation script.
 * Swap this for an API-backed adapter when scaling beyond static content.
 */
export class StaticArticleSource implements ArticleSource {
  private articles: FeedArticle[] = feedData as FeedArticle[];
  private metadata: FeedMetadata = metadataData as FeedMetadata;

  async getArticles(category?: HubCategory): Promise<FeedArticle[]> {
    if (!category) return this.articles;
    return this.articles.filter((a) => a.category === category);
  }

  async getArticle(id: string): Promise<FeedArticle | null> {
    return this.articles.find((a) => a.id === id) ?? null;
  }

  async getCategoryCounts(): Promise<Record<HubCategory, number>> {
    const counts: Record<string, number> = {
      dsa: 0,
      "system-design": 0,
      "ai-ml": 0,
      behavioral: 0,
      career: 0,
      general: 0,
    };

    for (const article of this.articles) {
      counts[article.category] = (counts[article.category] ?? 0) + 1;
    }

    return counts as Record<HubCategory, number>;
  }

  async getMetadata(): Promise<FeedMetadata> {
    return this.metadata;
  }
}
